package io.iohk.praos.crypto

import akka.util.ByteString

/**
  * VrfProof contains a fresh random value generated using the user public key, a random seed and
  * VerifiableRandomFunction.prove method. And also contains the proof, that will be used later,
  * with the user public key, for verify that the random value was generated by him.
  */
case class VrfProof(random: RandomValue, proof: ByteString)
